version: "3.3"
services:
  web:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - SECRET_KEY=1WBhgNHTUvD7Jnh6C
      - AUTH_REQUIRED=1
      - LOG_FORMAT=verbose
      - PORT=5001
      - DEBUG=1 # remove this line to turn DEBUG off
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
      - DASHBOARD_URL=http://127.0.0.1:5001
      - PLUGINS=reject,blackout,normalise,enhance,pushover
      - HEARTBEAT_POLL_TIME=30
      - HOUSE_POLL_TIME=60
      - ADMIN_KEY="FFFFFFFFFFFFFFFFFFFFFFFF"
      - ADMIN_USERS=tempuser
      - ALERTA_API_KEY="FFFFFFFFFFFFFFFFFFFFFFFF"
    restart: always
  db:
    image: postgres
    volumes:
      - /tmp/pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
